### ISSUE TITLE
Problem inferring clr type and unable to call inner classes

### ISSUE THREAD

**Issue by simendsjo** [IronScheme/IronScheme#122]
Maybe two different issues, but I'll just create the following for now.

```csharp
public class Outer
{
    public int i = 0;
}

public class Program
{
    public class Inner
    {
        public int i = 0;
    }
    
    public static void Main()
    {
        var o = new Outer();
        "(define o {0})".Eval(o);
        "(displayln o)".Eval(); // #<clr-type Outer>
        "(clr-field-get Outer i o)".Eval(); // OK
        /* But this fails
        "(clr-field-get #f i o)".Eval();
        &who: #f
        &message: "type not found"
        &syntax:
          form: #f
          subform: #f
        */

        var i = new Inner();
        "(define i {0})".Eval(i);
        "(displayln i)".Eval(); // #<clr-type Program+Inner>
        //"(clr-field-get Inner i i)".Eval(); // "type not found"
        //"(clr-field-get Program+Inner i i)".Eval(); // "type not found"
        //"(clr-field-get Program.Inner i i)".Eval(); // "type not found"
        //"(clr-field-get #f i i)".Eval(); // "field not found on type: Object"
    }
}
```

**Comment by leppie** [comment]
Tested on a latest build, but cant replicate. I know it was a bug a few months ago. Maybe you have an old build?

```
using IronScheme;

"(import (ironscheme clr))".Eval();

var o = new Outer();
"(define o {0})".Eval(o);
"(displayln o)".Eval();
"(clr-field-get Outer i o)".Eval(); 

var i = new Outer.Inner();
"(define i {0})".Eval(i);
"(displayln i)".Eval(); 
"(clr-field-get Outer+Inner i i)".Eval(); 

Console.WriteLine("done");

public class Outer
{
    public int i = 0;

    public class Inner
    {
        public int i = 1;
    }
}
```

As for inference, dont think there is any support.

**Comment by simendsjo** [comment]
Strange, your example breaks on my machine.

I created a new Console app for net6, referenced the newest IronScheme.Core, copied the `lib`-folder from the IronScheme console app (is this the problem..?) and pressed debug. Without copying the lib-folder, it breaks at `(import (ironscheme clr))` as the module cannot be found.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IronScheme.Core" Version="1.0.264" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="lib/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

<img width="941" alt="image" src="https://user-images.githubusercontent.com/351519/168985698-b93fd9df-378d-40b3-a4ba-cd4e655a21f1.png">

**Comment by simendsjo** [comment]
> Tested on a latest build, but cant replicate. I know it was a bug a few months ago. Maybe you have an old build?

I see version 282 is tagged and built, but 264 is the latest on nuget. Maybe the push to nuget fails silently?
@leppie: I see you don't monitor the repo actively, when do you want to get pinged?

**Comment by leppie** [comment]
> but 264 is the latest on nuget.

Latest build pushed too :D 



> Strange, your example breaks on my machine.

I had to copy the lib folder to the output folder :D
