### ISSUE TITLE
Can pretty-printing for quote/quasiquote/unquote be disabled for write or display?

### ISSUE THREAD

**Issue by leppie** [IronScheme/IronScheme#135]
### Discussed in https://github.com/IronScheme/IronScheme/discussions/133

<div type='discussions-op-text'>

<sup>Originally posted by **Zambito1** July 27, 2022</sup>
I'm looking to write expressions to a port which can be read and evaluated by a non-Scheme Lisp, and which does not use the same special syntax for quasiquote and unquote, but it uses the same quasiquote and unquote keywords.

Here is the behavior of Guile Scheme, which does what I would like:

```scheme
scheme@(guile-user)> (write (quote (quasiquote (foo (unquote x))))) (newline)
(quasiquote (foo (unquote x)))
scheme@(guile-user)> (write '`(foo ,x)) (newline)
(quasiquote (foo (unquote x)))
```

Contrast this with IronScheme:

```scheme
> (write (quote (quasiquote (foo (unquote x))))) (newline)
`(foo ,x)
> (write '`(foo ,x)) (newline)
`(foo ,x)
```

The output of Guile can be directly `(read)` by the other Lisp as I intend, but the special syntax used by `write` from IronScheme cannot be directly read. Is there a way to configure IronScheme to not use the special quasiquote and unquote characters for `write`?</div>

**Comment by leppie** [comment]
Would be possible. I will make a `parameter` for it.

**Comment by leppie** [comment]
Added in [1f71a063](https://github.com/IronScheme/IronScheme/commit/1f71a06382f6883c941eaf016b6613d6e2e46942)

Example usage:

```
> (write (quote (quasiquote (foo (unquote x))))) (newline)
`(foo ,x)
> (write '`(foo ,x)) (newline)
`(foo ,x)
> (shorthand-syntax-output #f)
> (write (quote (quasiquote (foo (unquote x))))) (newline)
(quasiquote (foo (unquote x)))
> (write '`(foo ,x)) (newline)
(quasiquote (foo (unquote x)))
>
```

Thanks for suggestion.

**Comment by leppie** [comment]
https://github.com/IronScheme/IronScheme/releases/tag/1.0.307

**Comment by Zambito1** [comment]
Thanks for this!
