### ISSUE TITLE
EvalWithEnvironment doesn't seem to work when given an importspec and arguments for substitution.

### ISSUE THREAD

**Issue by Zambito1** [IronScheme/IronScheme#136]
In the following block:

```csharp
Console.WriteLine("(+ 1 0)".Eval<int>());  // 1
Console.WriteLine("(+ 1 {0})".Eval<int>(1));  // 2
Console.WriteLine("(+ 1 2)".EvalWithEnvironment<int>("(interaction-environment)"));  // 3
Console.WriteLine("(+ 1 {0})".EvalWithEnvironment<int>("(interaction-environment)", 3));  // 4
Console.WriteLine("(+ 1 4)".EvalWithEnvironment<int>("(environment '(rnrs))"));  // 5
Console.WriteLine("(+ 1 {0})".EvalWithEnvironment<int>("(environment '(rnrs))", 5));  // 6
```

I receive the output:

```
1
2
3
4
5
```

But where I would expect `6` I instead receive the following error:

```
IronScheme.Runtime.SchemeException: a definition was found where an expression was expected
```

It seems like this is a bug in EvalWithEnvironment.

cc: @leppie

**Comment by leppie** [comment]
I think I know what the issue is, but if I am right, it might be hard to fix.

Thanks for spotting!

**Comment by leppie** [comment]
What is happening in the background is similar to the following, that fails too on Chez.

```
IronScheme Latest github.com/IronScheme © 2007-2021 Llewellyn Pritchard (.NET 2.0 32-bit)
> (eval '(begin (define (foo) 1) (foo)) (environment '(rnrs)))
Unhandled exception during evaluation:
&who: define
&message: "a definition was found where an expression was expected"
&syntax:
  form: (define (foo) 1)
  subform: #f
&trace: #<syntax (define (foo) 1)>
```

```
Chez Scheme Version 9.5.4
Copyright 1984-2020 Cisco Systems, Inc.

> (eval '(begin (define (foo) 1) (foo)) (environment '(rnrs)))
Exception: invalid definition in immutable environment (define (foo) 1)
Type (debug) to enter the debugger.
>
```

Obviously IronScheme does not have a very good error message. But the fact is that I am trying to mutate an immuatble environment with the substitution.

Perhaps for immuatble environments I should just keep it scoped as follows:

```
> (eval '(let () (define (foo) 1) (foo)) (environment '(rnrs)))
1
```

**Comment by Zambito1** [comment]
If the `let` solution is used instead, would the user be able to mutate bindings exported by the `(environment ...)` expression? It seems like the only requirement for the immutability of `(environment ...)` is that the bindings exported from that environment cannot be mutated.

> The bindings of the environment represented by the specifier are immutable: If eval is applied to an expression that is determined to contain an assignment to one of the variables of the environment, then eval must raise an exception with a condition type &assertion.

Source: http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-17.html#node_idx_1268

If the bindings exported by the `(environment ...)` are still immutable, I think that is a reasonable solution.

**Comment by leppie** [comment]
> If the `let` solution is used instead, would the user be able to mutate bindings exported by the `(environment ...)` expression?

Yes, it would just be 'shadowed' in the local scope.

**Comment by leppie** [comment]
Part 1 of the fix

Added `interaction-environment?` in [c5a26fd](https://github.com/IronScheme/IronScheme/commit/c5a26fdae2cf6511f1ee245d58cfa3a3828113b2)

```
> (interaction-environment? (scheme-report-environment 5))
#f
> (interaction-environment? (interaction-environment))
#t
> (interaction-environment? (new-interaction-environment))
#t
> (interaction-environment? (environment '(rnrs)))
#f
```

**Comment by leppie** [comment]
Part 2

Tests

```
// with this env needs to be extended, else define begin symbol-value may be unbound
var env = "(environment '(only (ironscheme) define begin symbol-value) '(rnrs))".Eval(); 
var ienv = "(interaction-environment)".Eval();
var newenv = "(new-interaction-environment)".Eval();

var r1 = "(+ 1 {0})".Eval(5);
var r2 = "(+ 1 {0})".EvalWithEnvironment("(environment '(rnrs))", 5);
var r3 = "(+ 1 {0})".EvalWithEnvironment("(interaction-environment)", 5);

var r4 = "(+ 1 {0})".EvalWithEnvironmentInstance(env, 5);
var r5 = "(+ 1 {0})".EvalWithEnvironmentInstance(ienv, 5);
var r6 = "(+ 1 {0})".EvalWithEnvironmentInstance(newenv, 5);
```

**Comment by leppie** [comment]
Not 100% ideal, but best effort for now.

Also added `EvalWithEnvironmentInstance` so you can now manage environment instances from the caller's side.

**Comment by leppie** [comment]
https://github.com/IronScheme/IronScheme/releases/tag/1.0.309

**Comment by leppie** [comment]
I have reworked the Eval code in the latest commit, let me know if you have issues.
