### ISSUE TITLE
Wrong target directory when compiling libraries

### ISSUE THREAD

**Issue by christoff-buerger** [IronScheme/IronScheme#147]
I am using IronScheme since a _long_ time. Recently I updated from 1.0.240 to the latest release, [1.0.320](https://github.com/IronScheme/IronScheme/releases/tag/1.0.320). [My Scheme project](https://github.com/christoff-buerger/racr) consists of a set of libraries and subprojects in various directories. I am using a set of Bash build scripts to compile all libraries; the scripts create binaries in _local_ subdirectories. I take care to include the local binary directories to the library path via the `-I` option when compiling or executing code.

After upgrading IronScheme from 1.0.240 to the latest release, the new version compiles the binaries always into IronScheme's installation directory. It seems impossible to select the target directory anymore. In my existing Bash build scripts I used a pipe of the form
```
cd target-binary-directory
echo "(compile \"target-binary-directory/compile-script.sls\")" | \
	mono "$( command -v IronScheme.Console-v4.exe )" -nologo "${library_paths[@]}"
```
IronScheme used to compile the libraries into the current workdirectory, for which reason I simply `cd` to the binary directory the dlls shall be compiled to. The compile script is simply importing all the libraries to compile; something like
```
(import
  (foo bar)
  (foo baz))
```
Above script now started to break; the compiled binary dlls end up in the installation directory of IronScheme and clutter it.

Is there any option to change the target directory?

Note: My system setup is an old MacBook air 2011 (Intel x86); I am using Mono 6.12.0.199 to run IronScheme.

**Comment by leppie** [comment]
This commit changed the behavior, but it seems I did think about backward compat.

https://github.com/IronScheme/IronScheme/commit/148e9fde30e409c884ce024d7409a223bfe4e215


To get your desired behavior:

```
(compile-to-current-directory? #t)
```

**Comment by leppie** [comment]
`(compile-to-current-directory? #t)` will become default again soon :D

**Comment by christoff-buerger** [comment]
> `(compile-to-current-directory? #t)` will become default again soon :D

Thanks a lot for the feedback! And all your hard work!

I will leave my explicit setting of `(compile-to-current-directory? #t)` for now and switch to the new-old default in a while.
