### ISSUE TITLE
Tail calls inside of a guard are not treated as tail calls.

### ISSUE THREAD

**Issue by Zambito1** [IronScheme/IronScheme#148]
Consider the following two blocks of code:

```scheme
(let loop ()
    (display "hello, world!\n")
    (loop))
```
```scheme
(let loop ()
    (guard (e (else (display e)))
      (display "hello, world!\n")
      (loop)))
```

Ideally they should behave the same I think. When I tested it in Guile Scheme, they do behave the same. When running the second expression on IronScheme with `IronScheme.Console-v4.exe`, it will print "hello, world" many times, and then crash with the error: `Process is terminated due to StackOverflowException.`. When running it on IronScheme with `dotnet IronScheme.ConsoleCore.dll`, it spits out a gigantic stack trace that runs off of my terminal history.

I realize that this may be related to the limits of continuations in IronScheme. I wonder if there is some kind of transformation that could be done to allow a tail call like this to be optimized still though.

In the meantime, if others run into this issue, a possible fix may be to move the tail call out side of the guard, if that works for your situation:

```scheme
(let loop ()
    (guard (e (else (display e)))
      (display "hello, world!\n"))
    (loop))
```

**Comment by leppie** [comment]
I think this is probably a limitation of where tail calls can be used on .NET. 

`guard` would be some form of a `try/catch` structure and if I recall, you can't have a tail call there (or you can, but it wont be tail called).

Thanks for noticing.

**Comment by leppie** [comment]
I would have to check the codegen, but a transform to something like this could work.

```
loop:

try
{
    if (condition)
    {
        throw new Exception();
    }
    goto loop;
}
catch
{
    Console.WriteLine("Error");
    goto loop;
}
```

`guard` however is a lot more complex than above for R6RS compat. 

Cant recall, but there could be a `fast-guard` or some similar proc somewhere in the code.

**Comment by leppie** [comment]
I dont think there is a gaurentee for call in   the tail position inside a `guard` to  be a  tail call.

As `guard` uses  `dynamic-wind`, it will will blow up  eventually on probably most Scheme's, It just  blows up   faster on IronScheme (I can  make that a little better).

Take  this  test code.

```
(let f ((i 0))
  (define (w s i)
    (lambda ()
      (write (list s i))
      (newline)))
  (dynamic-wind 
    (w 'in i)
    (lambda ()
      ((w 'proc i))
      (when (< i 2)
        (f (+ i 1))))
    (w 'out i)))  
```

On IronScheme  and  Chez  this  prints out:

```
(in 0)
(proc 0)
(in 1)
(proc 1)
(in 2)
(proc 2)
(out 2)
(out 1)
(out 0)
```

**Comment by leppie** [comment]
This killed Chez 32-bit

```
(let f ((i 0))
  (define (w s i)
    (lambda ()
      (write (list s i))
      (newline)))
  (dynamic-wind 
    values
    (lambda ()
      (when (< i 20000000000000000)
        (f (+ i 1))))
    (w 'out i))) 
```

```
out of memory
```
