### ISSUE TITLE
Library fails to compile on .NET Core

### ISSUE THREAD

**Issue by christoff-buerger** [IronScheme/IronScheme#152]
My [racr](https://github.com/christoff-buerger/racr) library works fine with IronScheme on mono. But I think mono has no future, so I started testing on .NET Core (the old version 6, because I am using an old Macbook Air 2011, with macOS 10.13 on Intel x64). I thought it will work out of the box, but no...

Note, that the library compiles and works fine for other R6RS Scheme systems (e.g., Chez, Sagittarius, Ypsilon, Larceny and IronScheme on mono).

The issue is, that I get compile errors:
```
compiling racr.core.dll
Failed to create language dictionary: Exception has been thrown by the target of an invocation.
Unhandled exception during evaluation:
&who: #f
&message: "Object reference not set to an instance of an object."
&syntax:
  form: #f
  subform: #f
```

The error message doesn't tell a lot, and it looks like some compiler internal issue.
Interestingly, I can import the file without issues and the library works fine.

You can test compiling the library by trying to compile https://github.com/christoff-buerger/racr/blob/master/racr/core.scm; that should yield above error.

**Comment by leppie** [comment]
This is a known issue.  https://github.com/IronScheme/IronScheme/discussions/99

You will have to compile with .NET desktop or Mono, then try load the compiled libraries with .NET Core (does not always work).

**Comment by christoff-buerger** [comment]
> This is a known issue. #99
> 
> You will have to compile with .NET desktop or Mono, then try load the compiled libraries with .NET Core (does not always work).

@leppie : Thanks for the feedback! I wasn't aware that .NET Core has such severe compilation issues (or should I say lacks support for compilation). This is no good news for .NET on non-Windows machines, considering Mono is no good either...

I read #99 but couldn't figure what your recommendation is? Just skip precompilation and stick with simple loading?

I honestly have issues to understand the issues of .NET Core; when I just load the libs from source, does it not have to jit compile stuff anyway? Is there some trick to store the results of such jit compilation? I hate the idea of things acting magically and stuff generated on the fly is stored somewhere, out of control of library users and developer. I usually follow the principle that my programs will only operate and manipulate a dedicated working directory and not magically cause artefacts to appear distributed all over the system.

**Comment by leppie** [comment]
> when I just load the libs from source, does it not have to jit compile stuff anyway?

This is really the only limitation. Once compiled, it runs just as fast. 

So only startup is slower, and it can get quite slow when a complex macro library has to be compiled.

**Comment by christoff-buerger** [comment]
> > when I just load the libs from source, does it not have to jit compile stuff anyway?
> 
> This is really the only limitation. Once compiled, it runs just as fast.
> So only startup is slower, and it can get quite slow when a complex macro library has to be compiled.

Thanks for the feedback. I understand that "not beeing capable to compile is not as bad as it sounds". I will consider supporting .NET Core as well.
