### ISSUE TITLE
Target .NET Framework 4 and overall "modernization"

### ISSUE THREAD

**Issue by kant2002** [IronScheme/IronScheme#154]
I did try out of curiousity build project, and discover following interesting properties
- Projects target net2.0
- Build works only on Windows
- Build depends in some small samples on Net Framework MSBuild
- Test project target 3.5
- Full sign (ilasm/ildasm does not support it on .NET)

I did try solve issues by myself, but I start thinking more about root cause of them.
Do you really need target .NET Framework 2.0 ? 
Is is possible to target .netstandard2.0 and don't bother with something else, I think it's fair right now. It's mostly about "not need to install anything". Developer pack for .NET Framework 3.5 is a hassle right now.

What about make sure that project can be built on Windows?

I know given how conservative you are (probably) I do want to ask your opinion about these "shaking"

**Comment by kant2002** [comment]
Other interesting [problems](https://github.com/dotnet/runtime/issues/11412) with .NET versions of ILAsm/ILDasm

**Comment by leppie** [comment]
I think at this point in time, there is probably not many more active Windows PC without .NET 4.

I would not be against changing to only .NET 4.x. 

We still need .NET desktop runtime for library compiling though. 

Also tests and artefact creation (in CI) would need to be addressed.

**Comment by leppie** [comment]
Would be nice to update get the profiler I wrote to work on CLR v4 too.  I think it just works on CLR v2.

Not critical, but from memory IronScheme has a tendency to kill tools like profilers and decompilers :D

**Comment by leppie** [comment]
As for singing assemblies, I think the only reason was to have safe for NGEN and other scenarios like running in Visual Studio. 

Not sure if this is still relevant.

**Comment by leppie** [comment]
Update README.md too.

**Comment by leppie** [comment]
Another thing is to target .NET Core 3 as a minimum (as that does not have issues loading precompiled libraries).

Ideally the bulk of the code should probably implement .NET Standard 2 (if that is possible at all).

**Comment by leppie** [comment]
Also drop Mono support if viable.

**Comment by leppie** [comment]
Resolved with [900e3d2](https://github.com/IronScheme/IronScheme/commit/900e3d209b47bdad64e54560e947f19c228c474b)
