### ISSUE TITLE
list-sort should be stable

### ISSUE THREAD

**Issue by weinholt** [IronScheme/IronScheme#60]
Hi @leppie,

The `list-sort` procedure in IronScheme does not implement the expected stable sort:

```scheme
> (list-sort (lambda (x y) (< (car x) (car y))) '((1 . a) (1 . b) (1 . c) (1 . d)))
((1 . c) (1 . d) (1 . a) (1 . b))
```

The expected result is `((1 . a) (1 . b) (1 . c) (1 . d)`. This was found by the test suite in my `compression` package.

Tested with IronScheme 1.0.221-82ba036  (.NET Core 3.0 64-bit).

**Comment by leppie** [comment]
Thanks. Seems `vector-sort` is also not stable as it uses `vector-sort!` which is not stable.

**Comment by leppie** [comment]
I just ended up stealing this guy's code :p 

https://github.com/weinholt/loko/blob/master/runtime/sorting.sls#L66

(thanks)

**Comment by weinholt** [comment]
The tests pass! Well taken code. (SLIB is great).
