### ISSUE TITLE
Detect if running on Mono, and mention it in logo/banner

### ISSUE THREAD

**Issue by lassik** [IronScheme/IronScheme#65]
When running on Mono, the IronScheme banner currently says:

```IronScheme 1.0.227-ddb210a ... (.NET Core 3.0 64-bit)```

Would be nice if the parentheses said that it's running on Mono. This helps differentiate between mono vs dotnet installations. We now have Docker images for both.

Here's a discussion of detecting Mono: https://stackoverflow.com/questions/721161/how-to-detect-which-net-runtime-is-being-used-ms-vs-mono

**Comment by leppie** [comment]
I didnt even know Mono can run .NET Core :D Serious question: Does it though?

More than likely I have some broken detection. 

I actually have that mono check in code already, I will add it to the banner.

**Comment by leppie** [comment]
I suspect runtime version display might still be wrong on Mono.

Thanks for report.

**Comment by lassik** [comment]
> I didnt even know Mono can run .NET Core :D Serious question: Does it though?

I don't know how the technicalities go. I thought it doesn't, but since .NET Core is now open source, Mono has probably imported at least some code from Microsoft.

Anyway, I pulled the newest IronScheme release and the detection now works just as expected:

```
$ docker run -it weinholt/ironscheme:dotnet
IronScheme 1.0.239-671ea21 github.com/IronScheme © 2007-2019 Llewellyn Pritchard (.NET Core 3.0 64-bit)
> ^D
$ docker run -it weinholt/ironscheme
IronScheme 1.0.239-671ea21 github.com/IronScheme © 2007-2019 Llewellyn Pritchard (Mono .NET 4.6 64-bit)
> ^D
```

Once again, thanks a lot for the quick turnaround :)

**Comment by leppie** [comment]
> Once again, thanks a lot for the quick turnaround :)

If only everything was this easy :D

**Comment by lassik** [comment]
Hehe, I know the feeling :)

Apparently the Mono version (`5.18.0.240`) is also different from their reported .NET version (`4.6`), which makes sense since the .NET version is probably the API version they track:

```
$ mono --version
Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019)
```

**Comment by leppie** [comment]
I dont have much patience for Mono. I will try easy workarounds, but I wont spare much effort on it.

**Comment by lassik** [comment]
It's probably fine to show the equivalent .NET API version in the banner, as it now stands.
