### ISSUE TITLE
Explicit /logo flag

### ISSUE THREAD

**Issue by lassik** [IronScheme/IronScheme#67]
(Related to #37)

Would it be possible to add an explicit `/logo` flag to complement `/nologo`? It would ensure that the startup banner is shown no matter what command name is used to run IronScheme.

Our current solution to show the banner when invoked as `scheme-banner` but hide it when invoked as `ironscheme` or `isc` is kind of a hack, relying on knowledge of magic behavior re: command names: https://github.com/weinholt/scheme-docker/blob/ironscheme/ironscheme/mono/ironscheme

**Comment by leppie** [comment]
Sorry for taking so long :D

**Comment by lassik** [comment]
No problem. Thanks for adding it!
