### ISSUE TITLE
Chocolatey package six years out of date

### ISSUE THREAD

**Issue by Chirishman** [IronScheme/IronScheme#71]
Hey, looks like your Chocolatey package for this was last updated in 2014 and still points to codeplex.

Please update it!

**Comment by leppie** [comment]
@Chirishman I have no idea how to even update or delete it...

**Comment by leppie** [comment]
Found a login! Attempting to unlist.

**Comment by leppie** [comment]
Error 524 Ray ID: 57c282f0c8024935 • 2020-03-30 14:27:28 UTC
A timeout occurred

**Comment by leppie** [comment]
I cant seem to get existing version unlisted for now. I have sent them a request to unlist all versions.
