### ISSUE TITLE
Copy/port old Codeplex docs to Github

### ISSUE THREAD

**Issue by leppie** [IronScheme/IronScheme#72]
It seems to Wayback machine captured data from the old codeplex site.

https://web.archive.org/web/20160421103033/http://ironscheme.codeplex.com/documentation

These docs should be ported to the Github Wiki.

**Comment by fubar-coder** [comment]
I converted the documentation: https://github.com/fubar-coder/IronScheme-Wiki

**Comment by leppie** [comment]
@fubar-coder Merged, thanks alot!
