### ISSUE TITLE
Concurrency support

### ISSUE THREAD

**Issue by bcalco** [IronScheme/IronScheme#74]
I understand from the disparate notes that `call/cc` is the one feature of Scheme *not* implemented in IronScheme, and I'm keen to understand if the main reason for that is level of effort being high, or simply the fact that access to full multicore programming via .NET makes it more pain than gain to implement? 

As a not-entirely side thought, one of my favorite features of Clojure is the Communicating Sequential Processes (CSP) support it "borrowed" from Go, and I observe with interest that the maintainer of Guile implemented a library on and for Guile called "fibers" that provides CSP to Guile. See:

- [Github repository](https://github.com/wingo/fibers)

- [Blog post describing motivation](https://wingolog.org/archives/2017/06/27/growing-fibers)

- [Wiki Manual](https://github.com/wingo/fibers/wiki/Manual)

- [Video talk where Wingo describes the implementation](https://www.youtube.com/watch?v=7IcI6sl5oBc)

I would be interested to see IronScheme be fully compliant with R6RS and implement `call/cc` per the spec (and I'm really starting to love Scheme and am sad for all the years I didn't learn it); however, I'd be happy (maybe even happier) to see CSP added to it with a nicer integration with .NET concurrency and parallel programming primitives. I am interested to work on it as well but wonder you (@leppie) think of one or both being core features of IronScheme out of the box perhaps?

**Comment by leppie** [comment]
There is a `call/cc` in IronScheme, but it is not a complete implementation. You can only do escape continuations, basically `call/ec` from Racket.

Native implementations dont have limits on the runtime, so it is easy for them to implement call/cc and/or fibers (aka green threads). With .NET (and probably JVM too), this is just not possible.

The only way to implement call/cc completely in .NET is to use CPS in the compiler. I did such an expirement before, and while it does work, it was horribly slow (10 times or more), and all the .NET interop pretty much goes out of the window.

Given that many Schemes already provide a proper call/cc and no .NET interop, I would suggest using them instead. IronScheme's niche is .NET interop.

**Comment by bcalco** [comment]
@leppie Within that niche, I'm sure there are some interesting concurrency extensions to IronScheme that are possible by wrapping the various concurrency libraries available in .NET. Just need to "think differently" about the problem, given that strict imitation of native Scheme's continuation-passing style and fibers a le Guile's implementation is more pain than gain to implement, per se.
